plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nexussec.launcher'
    compileSdk 34

    defaultConfig {
        applicationId 'com.nexussec.launcher'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

// Nessuna dipendenza: usiamo la WebView del framework Android (niente AndroidX).
dependencies {
}
